"""Initial migration with all models

Revision ID: 449c8ba5e934
Revises: 
Create Date: 2025-04-20 12:46:56.499168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449c8ba5e934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('stock_category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('serial_numbers', sa.String(length=500), nullable=True),
    sa.Column('acknowledgment_status', sa.String(length=20), nullable=False),
    sa.Column('acknowledgment_date', sa.DateTime(), nullable=True),
    sa.Column('acknowledgment_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['stock_category_id'], ['stock_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'stock_category_id', 'financial_year', 'invoice_number', name='uq_invoice_number_office_category_fy')
    )
    op.create_table('stock_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_category_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('reference_invoice', sa.String(length=100), nullable=True),
    sa.Column('serial_numbers', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['stock_category_id'], ['stock_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transaction')
    op.drop_table('invoice')
    op.drop_table('stock_category')
    op.drop_table('office')
    # ### end Alembic commands ###
