"""Add acknowledgment status and serial numbers

Revision ID: bf818be42e1c
Revises: 
Create Date: 2025-04-20 12:23:47.266929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf818be42e1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_numbers', sa.String(length=500), nullable=True))
        # First add acknowledgment_status as nullable
        batch_op.add_column(sa.Column('acknowledgment_status', sa.String(length=20), nullable=True))
        # Set default value for existing records
        op.execute("UPDATE invoice SET acknowledgment_status = 'PENDING' WHERE acknowledgment_status IS NULL")
        # Now make it non-nullable
        batch_op.alter_column('acknowledgment_status', nullable=False)
        
        batch_op.add_column(sa.Column('acknowledgment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acknowledgment_note', sa.String(length=200), nullable=True))

    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_invoice', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('serial_numbers', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transaction', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('serial_numbers')
        batch_op.drop_column('reference_invoice')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('acknowledgment_note')
        batch_op.drop_column('acknowledgment_date')
        batch_op.drop_column('acknowledgment_status')
        batch_op.drop_column('serial_numbers')

    # ### end Alembic commands ###
